In [13]:
import pandas as pd
  
# Creating the dataframe 
ratings = pd.read_csv('ContentBasedRecommenderSystem/ratings.csv', usecols=['userId','movieId','rating'])
movies = pd.read_csv('ContentBasedRecommenderSystem/movies.csv', usecols=['movieId','title'])
ratings_movies = pd.merge(ratings, movies, how='inner', on='movieId')
dfv1 = ratings_movies.pivot_table(index='title',columns='userId',values='rating')
dfv1 = dfv1.iloc[:,:200]#choose only 200 users
dfv1 = dfv1.dropna(thresh=3, axis=0)#remove any movies rated less than 3 times to reduce noise
# we used 2 variables here, dfv1 and df, because we will use the dataframe with the nans when we check whether a user watched a movie or not
df=dfv1.fillna(0,axis=0)#fill nan with zero
df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,191,192,193,194,195,196,197,198,199,200
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(500) Days of Summer (2009),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Cloverfield Lane (2016),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Things I Hate About You (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
"10,000 BC (2008)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

def standardize(column): #due to the NAN to zero replacement, we want to standarize the ratings to bring the mean to zero
    new_column = (column - column.mean())/(column.max()-column.min())
    return new_column

df_std = df.apply(standardize)

corrMatrix = pd.DataFrame(cosine_similarity(df_std),index=df.index,columns=df.index)
corrMatrix.head()

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",100 Girls (2000),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),102 Dalmatians (2000),12 Angry Men (1957),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),Â¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",1.000000,-0.109136,0.107435,0.148547,0.078624,0.130288,-0.058878,0.049650,0.177250,-0.143402,...,-0.001793,0.123596,0.140617,-0.083014,-0.153344,-0.162622,-0.062496,0.144315,0.109240,0.017333
(500) Days of Summer (2009),-0.109136,1.000000,0.068107,0.099559,-0.021163,-0.030254,0.000813,0.152343,0.068815,0.142447,...,0.226677,-0.024409,-0.163582,0.315660,0.386499,0.092847,0.263740,-0.099294,0.039081,0.007481
10 Cloverfield Lane (2016),0.107435,0.068107,1.000000,-0.133174,0.048762,0.090231,-0.083966,-0.009464,0.135179,-0.137392,...,0.219558,0.090709,-0.037729,0.091434,-0.003667,0.002297,0.301403,0.256580,-0.057458,-0.042443
10 Things I Hate About You (1999),0.148547,0.099559,-0.133174,1.000000,0.323869,0.310361,0.241822,0.139058,-0.041565,-0.105998,...,0.069798,-0.007383,-0.127737,-0.117775,0.098363,0.174849,-0.042932,0.019724,0.007970,-0.006196
"10,000 BC (2008)",0.078624,-0.021163,0.048762,0.323869,1.000000,0.923373,0.156567,-0.000423,0.098502,-0.205268,...,0.188645,0.052775,-0.096654,-0.002939,-0.020340,0.170066,-0.000626,-0.016727,0.089542,0.117952

In [15]:
def get_similar_given_movie(movie_name,number_of_movies):## takes movie name and the number of similar movies we want to return
    similarMovies=corrMatrix[movie_name].sort_values(ascending=False).index.to_list()
    if number_of_movies<len(similarMovies):
        return similarMovies[1:number_of_movies+1]# the first movie in this list will be the same movie that we passed to the function, so we exclude it
    else:
         return similarMovies[1:]



def get_similar_given_user(id_user):

    topRatedMovies=dfv1.iloc[:,id_user-1].dropna(axis=0).sort_values(ascending=False).index.to_list() #names of the  top rated ""watched""" movies by the user,,, 
    #(id_user-1) due to zero indexing,,,
    #dropna is used to drop the movies that the user didn't watch,    #note that we used (dfv1) , that has nan values#

    recommended_movies=[]


    #To recommend 3 movies to a user
    # we have 2 options, either we choose one movie the user watched and liked most, then recommend 3 movies similar to it , 
    # or we choose 3 movies the user liked, and get one similar movie to each one of them
    #but we should make sure that the user didn't watch the movies that we will recommnend


    # we chose the 2nd option, to get 3 movies the user liked, and get one similar movie to each one of them
    num_movies_recommended=3
    for i in range (num_movies_recommended) : 
        movies=get_similar_given_movie(movie_name=topRatedMovies[i],number_of_movies=20)# get 20 movies similar to the ith movie that the user liked

        for movie in movies: 
            
            if movie not in topRatedMovies: #if the movie we found hasn't been watched by the user yet
                recommended_movies.append(movie)#then, recommend it
                break
            ##we assumed that we will find a movie the user didn't watch in the 20 movie that we got, so no else statement

    return recommended_movies

In [16]:
print(get_similar_given_movie(movie_name='Toy Story (1995)',number_of_movies=10),"\n")



print(get_similar_given_movie(movie_name='Waiting to Exhale (1995)',number_of_movies=10),"\n")


print(get_similar_given_user(id_user=200))

['Pulp Fiction (1994)', 'Independence Day (a.k.a. ID4) (1996)', 'Aladdin (1992)', 'Mission: Impossible (1996)', 'Jurassic Park (1993)', 'Star Wars: Episode IV - A New Hope (1977)', 'Shrek (2001)', 'Shawshank Redemption, The (1994)', 'Mask, The (1994)', 'Braveheart (1995)']

['Only You (1994)', 'Cobb (1994)', 'Before and After (1996)', 'Candidate, The (1972)', 'Queen Margot (Reine Margot, La) (1994)', 'When a Man Loves a Woman (1994)', 'Fatal Instinct (1993)', 'Mighty Morphin Power Rangers: The Movie (1995)', 'Speechless (1994)', "What's Love Got to Do with It? (1993)"]

['Matilda (1996)', 'Bridesmaids (2011)', 'Into the Wild (2007)']